---

- include: manage-instances.yml
  when: manage_instances == "yes"

- include: manage-groups.yml
  when: manage_groups == "yes"

- include: create-groups.yml
  when: create_groups == "yes"

- include: create-instances.yml	
  when: create_instances == "yes"