---
- name: Take {{sg}} Security Group down
  ec2_group:
      name: "{{ansible_local.operations.manage.sg}}"
      description: "A Security group"
      region: "{{ansible_local.operations.general.region}}"
      state: 'absent'