---
# Basic decommissioning example


- name: Doing {{action}} to {{ec2_id}} instance in {{aws_region}}
  local_action:
      module: ec2
      state: '{{action}}'
      region: '{{aws_region}}'
      instance_ids: '{{ec2_id}}'


- name: Take {{sg}} Security Group down
  local_action:
      module: ec2_group
      name: "{{sg}}"
      description: "A Security group"
      region: "{{aws_region}}"
      state: 'absent'
  when: action == "absent"