---

- name: "Doing {{action}} to {{ec2_id}} instance in {{region}}"
  ec2:
      state: "{{action}}"
      region: "{{region}}"
      instance_ids: "{{ec2_id}}"
      instance_tags:
        Name: holamundo

- name: Take {{sg}} Security Group down
  ec2_group:
      name: "security_group_{{sg}}"
      description: "A Security group"
      region: "{{region}}"
      state: 'absent'
  when: action == "absent"