- name: Manage AWS
  hosts: "{{group_managed}}"
  # hosts: aws
  connection: local
  gather_facts: True
  sudo: True
  sudo_user: usuariolinux

  roles:
    - { role: aws-vpc, tags: vpc }
    - { role: aws-tool, tags: tool, required_vars: action}
